- name: Host initial setup
  hosts: all
  become: true
  tasks:
    - name: Setting timezone
      timezone:
        name: Asia/Jakarta

    - name: Setting hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Install requirements
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - chrony
          - rsync
          - net-tools
          - iotop
          - sysstat
          - python3-psycopg2
        state: present
        update_cache: true
      register: apt_result
      retries: 5
      delay: 15
      until: apt_result is succeeded

    - name: Force ntp sync
      shell: "chronyc -a makestep"

    - name: Disable swap partition
      shell: "swapoff -a"

    - name: Disable swap partition permanently
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap\s+sw\s+.*'
        state: absent
