- name: Create User With sudo
  hosts: all
  become: true
  vars:
    new_user_name: "{{ lookup('ansible.builtin.env', 'USER', default=Undefined) }}"
    new_user_ssh_key: "{{ lookup('ansible.builtin.env', 'USER_SSH_KEY', default=Undefined) }}"
  tasks:
    - name: Add user
      user:
        shell: "/bin/bash"
        name: "{{ new_user_name }}"
        password: "!"

    - name: Ensure .ssh directory exists
      when: new_user_ssh_key is defined
      file:
        path: "/home/{{ new_user_name }}/.ssh"
        state: directory
        owner: "{{ new_user_name }}"
        group: "{{ new_user_name }}"
        mode: 0700

    - name: Add ssh key
      when: new_user_ssh_key is defined
      authorized_key:
        key: "{{ new_user_ssh_key }}"
        user: "{{ new_user_name }}"

    - name: Add user to sudoers
      copy:
        content: '{{ new_user_name }} ALL=(ALL) NOPASSWD:ALL'
        dest: "/etc/sudoers.d/{{ new_user_name }}"
        mode: 0440
