---
- name: Install MicroK8s
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install snapd
      apt:
        name: snapd
        state: present
      when: ansible_os_family == "Debian"

    - name: Install MicroK8s via snap
      community.general.snap:
        name: microk8s
        classic: yes
        state: present

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      changed_when: false
      register: microk8s_status
      until: microk8s_status.rc == 0
      retries: 30
      delay: 10

    - name: Add current user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    - name: Create .kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Generate kubeconfig
      command: microk8s config
      register: kubeconfig
      changed_when: false

    - name: Save kubeconfig
      copy:
        content: "{{ kubeconfig.stdout }}"
        dest: "/home/{{ ansible_user }}/.kube/config"
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Enable basic MicroK8s addons
      command: "microk8s enable dns storage ingress"
      changed_when: true

    - name: Show MicroK8s status
      command: microk8s status
      register: final_status
      changed_when: false

    - name: Display MicroK8s status
      debug:
        var: final_status.stdout_lines